### ISSUE TITLE
Custom palette does not show on canvas

### ISSUE THREAD

**Issue by wsteven24** [camunda-community-hub/camunda-modeler-plugin-reduced-palette#4]
Hello! 
Please I need help. I’ve downloaded the code but the custom palette does not show up. No errors are shown neither when building nor runtime (dev console).

Steps to replicate:
1) download the code
2) put into the plugins folder
3) restart camunda modeler

Camunda Modeler version: 5.0.0-alpha.1
SO: Windows 10

**Comment by celanthe** [comment]
Hi @wsteven24! Thank you kindly for opening this issue. I would humbly propose that you also post this question on the [BPMN.io community forums](https://forum.bpmn.io/) if possible, as you will likely get a quicker response there.

**Comment by Skaiir** [comment]
Hi @wsteven24.

We've had a look at this internally and, as the labels suggest this is an unmaintained plugin. It seems that back to at least v4.7.0 it hasn't been functional. This would need a bit of adaptation to work in newer versions of the modeler.

We're open to contributions of course, and I would suggest any migration to use the configuration files from the [plugin starter project](https://github.com/camunda/camunda-modeler-plugin-example) (for things like webpack). [The Palette API](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/palette/Palette.js) can be used as a reference point to get started.

**Comment by wsteven24** [comment]
Thank you so much guys! The links you provided helped a lot and I was able to solve the problem. Just in case someone else has the same problem, I did the following changes to the code:

1) index.js
```
import { registerBpmnJSPlugin } from 'camunda-modeler-plugin-helpers';
import customPalettePlugin from './customPalette/CustomPaletteProvider';

const customPaletteBpmnJSPlugin = {
  __init__: [ 'paletteProvider' ],
  paletteProvider: [ 'type', customPalettePlugin ]
};

registerBpmnJSPlugin(customPaletteBpmnJSPlugin);
```

2) delete the client/ReducedPalettePlugin.js

3) client/customPalette/CustomPaletteProvider.js
```
import {assign} from 'min-dash';

 export default function PaletteProvider(palette, create, elementFactory, bpmnFactory, spaceTool, lassoTool, handTool, globalConnect, translate) {

   this._palette = palette;
   this._create = create;
   this._bpmnFactory = bpmnFactory;
   this._elementFactory = elementFactory;
   this._spaceTool = spaceTool;
   this._lassoTool = lassoTool;
   this._handTool = handTool;
   this._globalConnect = globalConnect;
   this._translate = translate;

   palette.registerProvider(this);
 }

PaletteProvider.$inject = [ 
  'palette', 
  'create', 
  'elementFactory', 
  'bpmnFactory',
  'spaceTool', 
  'lassoTool',
  'handTool', 
  'globalConnect', 
  'translate' 
];
...
```

4) package.json
```
 ...
  "devDependencies": {
    "camunda-modeler-plugin-helpers": "^5.0.0",
    "browserify": "^14.1.0",
   ...
  },
  "dependencies": {
    "bpmn-js": "^9.0.3",
    "diagram-js": "^3.0.0",
    "inherits": "^2.0.1",
    "min-dash": "^3.0.0",
    ...
  },
 ...

```

Thanks a lot for your kind help :-)
